In [107]:
import numpy as np
def conv(inp_mat,conv_mat):
    (a,b) = conv_mat.shape
    (x,y) = inp_mat.shape
    out_mat = np.zeros(inp_mat.shape)
    inp_mat = np.pad(inp_mat,(a//2,b//2), 'constant', constant_values=0)
    #print(inp_mat)
    
    #print(x,y,a,b)
    for i in range(x):
        for j in range(y):
            temp = 0
            for ci in range(a):
                for cj in range(b):
                    #print(i,j,ci,cj)
                    temp += inp_mat[i+ci,j+cj]*conv_mat[ci,cj]
            out_mat[i,j] = temp
    
    return out_mat

In [108]:
inp = np.array([[164,188,164,161,195],[178,201,197,150,137],[174,168,181,190,184],[131,179,176,185,198],[92,185,179,133,167]])
inp

array([[164, 188, 164, 161, 195],
       [178, 201, 197, 150, 137],
       [174, 168, 181, 190, 184],
       [131, 179, 176, 185, 198],
       [ 92, 185, 179, 133, 167]])

In [109]:
conm = np.array([[1,1,1],[1,1,1],[1,1,1]])
conm


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [110]:
out1 = conv(inp,conm)
out1

array([[ 731., 1092., 1061., 1004.,  643.],
       [1073., 1615., 1600., 1559., 1017.],
       [1031., 1585., 1627., 1598., 1044.],
       [ 929., 1465., 1576., 1593., 1057.],
       [ 587.,  942., 1037., 1038.,  683.]])

In [111]:
conm1 = np.array([[-1,-2,-1],[0,0,0],[-1,-2,-1]])
conm1

array([[-1, -2, -1],
       [ 0,  0,  0],
       [-1, -2, -1]])

In [113]:
out2 = conv(inp,conm1)
out2

array([[ -557.,  -777.,  -745.,  -634.,  -424.],
       [-1032., -1395., -1397., -1426., -1109.],
       [ -998., -1442., -1461., -1378., -1005.],
       [ -885., -1332., -1396., -1357., -1025.],
       [ -441.,  -665.,  -716.,  -744.,  -581.]])

In [114]:
conm3 = np.array([[-1,-1,-1],[-1,9,-1],[-1,-1,-1]])
conm3

array([[-1, -1, -1],
       [-1,  9, -1],
       [-1, -1, -1]])

In [115]:
out3 = conv(inp,conm3)
out3

array([[ 909.,  788.,  579.,  606., 1307.],
       [ 707.,  395.,  370.,  -59.,  353.],
       [ 709.,   95.,  183.,  302.,  796.],
       [ 381.,  325.,  184.,  257.,  923.],
       [ 333.,  908.,  753.,  292.,  987.]])